version: '3.5'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    container_name: users_service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    image: users_api_rest
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    networks:
      - internal
    stdin_open: true
    tty: true

  postgres:
    container_name: users_database
    image: postgres:11.3
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./envs/local
    networks:
      - internal

networks:
  internal:
